name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      #     - name: Build the Docker image
      #       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker-compose
      - name: Wait for the database to be up and running
        run: docker-compose run app sh -c "python manage.py wait_for_db"
      - name: Test django app with docker
        run: docker-compose run app sh -c "python manage.py python manage.py test && flake8"
